version: "3"
services:
  dbeaver:
    image: "dbeaver/cloudbeaver:latest"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 120s
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace
    networks:
      - internal

networks:
  internal:
    external: true

volumes:
    dbeaver-data:

