version: '3.2'

services:
  smr-api:
    image: smrvanchuyenquocte/logisticservice:latest
    networks:
      - internal
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 500M
      mode: replicated
      replicas: 2

networks:
  internal:
    external: true

